project:
  type: website
 
website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1A
            href: hands_on_ex\hands_on_ex1\hands-on_ex1.qmd
          - text: Hands-on Exercise 1B
            href: hands_on_ex\hands_on_ex1b\hands_on_ex1b.qmd
          - text: Hands-on Exercise 2
            href: hands_on_ex\hands_on_ex2\hands_on_ex2.qmd
          - text: Hands-on Exercise 3
            href: hands_on_ex\hands_on_ex3\hands_on_ex3.qmd
          - text: Hands-on Exercise 4
            href: hands_on_ex\hands_on_ex4\hands_on_ex4.qmd
      - text: In-Class Exercises
        menu: 
          - text: In-Class Exercise 1
            href: in_class_ex\ex1\in-class-ex1.qmd
          - text: In-Class Exercise 2
            href: in_class_ex\ex2\in-class-ex2.qmd
          - text: In-Class Exercise 3
            href: in_class_ex\ex3\in_class_ex3.qmd
          - text: In-Class Exercise 4
            href: in_class_ex\ex4\in_class_ex4.qmd
      - text: Take-Home Exercises
        menu: 
          - text: Take-Home Exercise 1
            href: take_home_ex\ex1\take-home-ex1.qmd
            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual